version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
    volumes:
       - /tmp/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
